repo:
    https://github.com/avinashmane/colab.git
packages: 
- chromium-chromedriver
modules:
- nerodia
- pygsheets

env:
    nt:
        LIB: c:/m/lib
        LOG: c:/m/social-media-automation
        AUTH: c:/i/auth
    posix:
        LIB: /content/drive/MyDrive/m/lib
        LOG: /content/drive/MyDrive/m/lib
        AUTH: /content/drive/MyDrive/m/auth
sheets:
    stravasync:
        url: https://docs.google.com/spreadsheets/d/1Q8SA641P0aytWzPGmeHG_xuxll3Wq6phsxjb91RjgWY/edit#gid=0
        tab: Members
        range: A10:O
    StravaPromoLog:
        url: https://docs.google.com/spreadsheets/d/14a8u53o0V6jKwP1nxk0334jvKsRnW6J5hKzcaQAwUbw/edit#gid=179675201
        tab: StravaPromoLog
    certs:
        url: https://docs.google.com/spreadsheets/d/1uuw1oavkE7Ahr1h-mmkSaNhR-MUcVRER5KVSyLM7Ot0/edit#gid=1084861083
        tab: RunDayCerts        
        
strava:
  avinash:
    clubs:
     - https://www.strava.com/clubs/delhirunnersgroup
  strava_pcmcrunners:
    clubs:
  mileage_league_strava:
    clubs:
     - https://www.strava.com/clubs/mileageleague
     - https://www.strava.com/clubs/pcmcrunners
     - https://www.strava.com/clubs/prettycoolmileagechallenge
     - https://www.strava.com/clubs/pcmcbikers
     - https://www.strava.com/clubs/punecycling
     - https://www.strava.com/clubs/didyouruntoday
     - https://www.strava.com/clubs/PuneWalkers
     - https://www.strava.com/clubs/prettycoolmileagechallenge
     - https://www.strava.com/clubs/mileageleague
     - https://www.strava.com/clubs/weekendriderspune
     - https://www.strava.com/clubs/cycleforpune
     - https://www.strava.com/clubs/pcmcrunners
  unused:
    clubs:
     - https://www.strava.com/clubs/indiancyclingclub
     - https://www.strava.com/clubs/5000kmchallenge
     - https://www.strava.com/clubs/1000Kms
     - https://www.strava.com/clubs/6000Kms
     - https://www.strava.com/clubs/5000kms
     - https://www.strava.com/clubs/Kolhapur
     - https://www.strava.com/clubs/4000Kms
     - https://www.strava.com/clubs/3000-Kms
     - https://www.strava.com/clubs/10000Kms-ride
     - https://www.strava.com/clubs/Strava-India-Cycling
     - https://www.strava.com/clubs/stravaphotos
     - https://www.strava.com/clubs/-TCC
     - https://www.strava.com/clubs/reebokrun
     - https://www.strava.com/clubs/Run_The_Year
     - https://www.strava.com/clubs/DHMP
     - https://www.strava.com/clubs/stravaindiaclub
     - https://www.strava.com/clubs/CyclingForLife
     - https://www.strava.com/clubs/cyclingweekly
other:     
     - https://www.strava.com/clubs/332676
     - https://www.strava.com/clubs/202omilesin2020
     - https://www.strava.com/clubs/delhirunnersgroup
listClubs:
